const aluno01 = "Mayk"
const notaaluno01 = 9.8

const aluno02 = "diego"
const notaaluno02 = 10

const aluno03 = "miche"
const notaaluno03 = 2

const media = (notaaluno01 + notaaluno02 + notaaluno03) / 3


// se a media for maior que 5, parabenizar a turma
if (media > 5) {
 console.log(`parabens seus Fdp, a media foi ${media}`)
 // faz alguma coisa
} else {
 console.log('VAI ESTUDAR SEUS FDPPP')
}
